#!/usr/bin/env nix-shell
#!nix-shell -i bash -p bash jq gawk gnused
#!nix-shell -p git nix-prefetch-git gnugrep coreutils
#
# shellcheck shell=bash

set -euo pipefail

QMK_REPO="${QMK_REPO:-https://github.com/qmk/qmk_firmware.git}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
CACHE_DIR="${CACHE_DIR:-$REPO_ROOT/firmware/versions}"
OUT_FILE="${OUT_FILE:-$REPO_ROOT/firmware/versions.nix}"
JOBS="${JOBS:-$(nproc)}"

git_https() {
  git \
    -c 'url."https://github.com/".insteadOf=git@github.com:' \
    -c 'url."https://github.com/".insteadOf=ssh://git@github.com/' \
    "$@"
}

echo "Fetching tags..." >&2

tags=$(
  git_https ls-remote --tags "$QMK_REPO" |
    awk '{print $2}' |
    sed 's#refs/tags/##' |
    sed 's/\^{}//' |
    grep -E '^(v?[0-9]+\.[0-9]+\.[0-9]+)$' |
    uniq |
    sort --version-sort
)

mkdir --parents "$CACHE_DIR"

echo "Fetched $(wc -l <<<"$tags") tags." >&2

fetch_one() {
  local version="$1"
  local cache="$CACHE_DIR/$version"
  local hash json

  if [[ -f $cache ]]; then
    hash="$(<"$cache")"

    if [[ -n $hash ]]; then
      printf '%s %s\n' "$version" "$hash"
      return
    fi

    echo "WARNING: $cache is empty, retrying..." >&2
    rm --force -- "$cache"
  fi

  json="$(
    nix-prefetch-git \
      --url "$QMK_REPO" \
      --rev "$version" \
      --fetch-submodules \
      --no-add-path \
      --quiet
  )"

  hash="$(jq --raw-output .hash <<<"$json")"

  printf '%s\n' "$hash" >"$cache"
  printf '%s %s\n' "$version" "$hash"
}

export -f fetch_one
export QMK_REPO CACHE_DIR

echo "Prefetching hashes in parallel..." >&2

results="$(
  printf '%s\n' "$tags" |
    xargs -r -n1 -P "$JOBS" bash -c 'fetch_one "$1"' _
)"

echo "Generating Nix file..." >&2

tmp_file="$(mktemp)"
trap 'rm --force "$tmp_file"' EXIT

declare -A latest_by_major
declare -A latest_by_minor
declare -A hashes

latest_version=""

while read -r version hash; do
  hashes["$version"]="$hash"

  version_no_v="${version#v}"
  IFS='.' read -r major minor patch <<<"$version_no_v"

  latest_by_major["v$major"]="v${version_no_v//./_}"
  latest_by_minor["v${major}_$minor"]="v${version_no_v//./_}"

  latest_version="$version"
done < <(
  printf '%s\n' "$results" |
    sort --key=1 --version-sort
)

latest_attr="v${latest_version#v}"
latest_attr="${latest_attr//./_}"

{
  echo '# This file is automatically generated. Do NOT edit manually.'
  echo '# To regenerate, run `nix run .#update-firmware`, or run the'
  echo '# underlying `firmware/update.bash` script directly.'
  echo
  echo '{'
  echo '  fetchQmkFirmware,'
  echo '}:'
  echo
  echo 'rec {'
  echo "  latest = $latest_attr;"

  echo
  for alias in "${!latest_by_major[@]}"; do
    echo "  $alias = ${latest_by_major[$alias]};"
  done | sort

  echo
  for alias in "${!latest_by_minor[@]}"; do
    echo "  $alias = ${latest_by_minor[$alias]};"
  done | sort

  echo
  while read -r version; do
    version_no_v="${version#v}"
    attr="v${version_no_v//./_}"

    cat <<EOF
  $attr = fetchQmkFirmware {
    tag = "$version";
    hash = "${hashes[$version]}";
  };

EOF
  done < <(
    printf '%s\n' "$tags" |
      sort --reverse --version-sort
  )

  echo '}'
} >"$tmp_file"

mv -- "$tmp_file" "$OUT_FILE"

echo "Done. Wrote $OUT_FILE" >&2
