#!/usr/bin/env nix-shell
#!nix-shell -i bash -p bash jq gawk gnused
#!nix-shell -p git nix-prefetch-git gnugrep
#
# shellcheck shell=bash

set -euo pipefail

QMK_REPO="${QMK_REPO:-"https://github.com/qmk/qmk_firmware.git"}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
CACHE_DIR="${CACHE_DIR:-"$REPO_ROOT/firmware/versions"}"
OUT_FILE="${OUT_FILE:-"$REPO_ROOT/firmware/versions.nix"}"

git-https() {
  git -c 'url."https://github.com/".insteadOf="git@github.com:"' \
    -c 'url."https://github.com/".insteadOf="ssh://git@github.com/"' \
    "$@"
}

echo "Fetching tags..." >&2
tags=$(
  git-https ls-remote --tags "$QMK_REPO" |
    awk '{print $2}' |
    sed 's#refs/tags/##' |
    sed 's/\^{}//' |
    grep -E '^(v?[0-9]+\.[0-9]+\.[0-9]+)$' |
    uniq | sort --version-sort
)

# Make sure CACHE_DIR is an existing directory
if [ ! -d "$CACHE_DIR" ]; then
  rm --recursive "$CACHE_DIR" --force
  mkdir --parents "$CACHE_DIR"
fi

echo "Fetched tags..." >&2

format_version_hash() {
  version="$1"
  hash="$2"
  # key="v${version//./_}"
  printf -v result '  "%s" = "%s";' "$version" "$hash"
  tee /dev/stderr <<<"$result"
}

fetch_one() {
  version="$1"
  cache="$CACHE_DIR/$version"

  if [[ -f $cache ]]; then
    hash="$(cat "$cache")"
    if [[ -n $hash ]]; then
      format_version_hash "$version" "$hash"
      return
    else
      echo "  WARNING: $cache is empty, trying again..." >&2
      rm -- "$cache"
    fi
  fi

  json=$(
    nix-prefetch-git \
      --url "$QMK_REPO" \
      --rev "$version" \
      --fetch-submodules \
      --no-add-path \
      --quiet
  )

  hash=$(echo "$json" | jq -r .hash)
  format_version_hash "$version" "$hash"
  echo "$hash" >"$cache"
}

export -f git-https fetch_one format_version_hash
export QMK_REPO OUT_FILE CACHE_DIR REPO_ROOT

echo "Processing tags in parallel..." >&2

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

{ # replacing the versions file atomically.
  echo $'# This file is automatically generated. Do NOT edit manually.'
  echo $'# To regenerate, run `nix run .#update-firmware`, or run the'
  echo $'# underlying `firmware/update.bash` script directly.'
  echo $''
  echo $'{'
  echo "$tags" |
    xargs -I{} -P 16 bash -c 'fetch_one "$@"' _ {} |
    sort --reverse --version-sort
  echo $'}'
} >"$tmp_file"

echo "Done processing tags." >&2
mv "$tmp_file" "$OUT_FILE"
