name: Checks
# Updates the firmware cache once every week.

on:
  workflow_dispatch:
  push:
    branches: [main, master, release, development]
    paths: [.github/workflows/many--basic-ci-checks.yaml.yaml, '**/*.nix', flake.lock]
  pull_request:
    branches: [main, master, release, development]
    types: [opened, synchronize, reopened]
    paths: [.github/workflows/many--basic-ci-checks.yaml.yaml, '**/*.nix', flake.lock]

jobs:
  update-firmware:
    name: Check ${{ github.event_name == 'pull_request' && 'your Pull Request' || 'Latest Changes' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup unused space for disk
        run: | 
          echo "::group::Free space before cleanup" 
          df -h 
          echo "::endgroup::" 
          echo "::group::Cleaned Files" 
          sudo rm -rfv ${{ runner.os == 'Linux' && '/usr/local/lib/android' || '/Users/runner/Library/Android/sdk' }} 
          echo "::endgroup::" 
          echo "::group::Free space after cleanup" 
          df -h 
          echo "::endgroup::" 
      - name: Checkout repository
        uses: actions/checkout@v6.0.3
      - name: Install Nix using cachix
        uses: cachix/install-nix-action@v31.7.0
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7.0.2
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 10G
          purge: true
      - name: Check tests in parallel
        run: nix flake check --print-build-logs --show-trace
